# -*- coding: utf-8 -*-
"""Honeywell.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13J2qHeUebb7Ni1i_bjDCeTy_hMNay3LL
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ai4i2020.csv')
df.head()

df.info()
df.describe()

# Drop useless columns
df = df.drop(["UDI", "Product ID"], axis=1)

# Encode categorical
df["Type"] = df["Type"].map({"L": 0, "M": 1, "H": 2})

# Feature Fusion
df["Temp_diff"] = df["Process temperature [K]"] - df["Air temperature [K]"]
df["Power"] = df["Rotational speed [rpm]"] * df["Torque [Nm]"]

# Improved features
df["Torque_per_speed"] = df["Torque [Nm]"] / (df["Rotational speed [rpm]"] + 1)
df["Wear_rate"] = df["Tool wear [min]"] / (df["Rotational speed [rpm]"] + 1)

# Failure type (innovation)
failure_cols = ["TWF", "HDF", "PWF", "OSF", "RNF"]
df["Failure Type"] = df[failure_cols].idxmax(axis=1)

# Split
X = df.drop(["Machine failure", "Failure Type"] + failure_cols, axis=1)
y = df["Machine failure"]

feature_names = X.columns

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

scaler = StandardScaler()
X_resampled = scaler.fit_transform(X_resampled)
X_test_scaled = scaler.transform(X_test)

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_resampled.shape[1],)),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['Recall']
)

model.fit(
    X_resampled, y_resampled,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
import numpy as np

input_dim = X_resampled.shape[1]

input_layer = Input(shape=(input_dim,))
encoded = Dense(32, activation="relu")(input_layer)
encoded = Dense(16, activation="relu")(encoded)

decoded = Dense(32, activation="relu")(encoded)
decoded = Dense(input_dim, activation="linear")(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)
autoencoder.compile(optimizer="adam", loss="mse")

# Train on NORMAL data only
X_normal = X_resampled[y_resampled == 0]

autoencoder.fit(
    X_normal, X_normal,
    epochs=20,
    batch_size=32,
    validation_split=0.1,
    verbose=0
)

# Reconstruction error
reconstructions = autoencoder.predict(X_test_scaled)
mse = np.mean((X_test_scaled - reconstructions) ** 2, axis=1)

# use only NORMAL data to set threshold
recon_train = autoencoder.predict(X_resampled[y_resampled == 0], verbose=0)
train_mse = np.mean((X_resampled[y_resampled == 0] - recon_train)**2, axis=1)

anomaly_threshold = np.percentile(train_mse, 99)
anomaly_flags = (mse > anomaly_threshold).astype(int)

prob = model.predict(X_test_scaled).flatten()

threshold = 0.3
y_pred = (prob > threshold).astype(int)

def get_root_cause(sample_scaled, model, top_k=2):
    baseline = model.predict(sample_scaled)[0][0]

    importances = []

    for i in range(sample_scaled.shape[1]):
        modified = sample_scaled.copy()
        modified[0][i] = 0

        new_pred = model.predict(modified)[0][0]
        impact = abs(baseline - new_pred)

        importances.append((feature_names[i], impact))

    importances.sort(key=lambda x: x[1], reverse=True)
    return importances[:top_k]

def risk_level(score):
    if score > 0.7:
        return "HIGH"
    elif score > 0.4:
        return "MEDIUM"
    else:
        return "LOW"

def confidence_level(p):
    if abs(p - 0.5) < 0.1:
        return "UNCERTAIN"
    elif p > 0.8 or p < 0.2:
        return "HIGH CONFIDENCE"
    else:
        return "MODERATE"

def maintenance_action(pred, anomaly, causes, sample):

    if pred == 1:
        top_feature = causes[0][0]

        if "Tool wear" in top_feature:
            return "🔧 Replace tool (high wear)"

        elif "Torque" in top_feature:
            return "⚠️ Check motor load"

        elif "temperature" in top_feature.lower():
            return "🌡️ Inspect cooling system"

        elif anomaly == -1:
            return "🚨 Unexpected anomaly → full inspection"

        else:
            return "🛠 Preventive maintenance"

    return "✅ Normal operation"

import time

print("------ ADVANCED MONITORING SYSTEM ------")

for i in range(5):
    sample = X_test.iloc[i]
    sample_scaled = scaler.transform([sample])

    prob_val = model.predict(sample_scaled)[0][0]
    pred = int(prob_val > threshold)

    # Autoencoder anomaly
    recon = autoencoder.predict(sample_scaled)
    mse_val = np.mean((sample_scaled - recon)**2)
    anomaly = -1 if mse_val > anomaly_threshold else 1

    # Root cause
    causes = get_root_cause(sample_scaled, model)

    # Fusion score
    normalized_mse = min(mse_val / anomaly_threshold, 1)
    final_score = 0.7 * prob_val + 0.3 * normalized_mse

    risk = risk_level(final_score)
    confidence = confidence_level(prob_val)

    action = maintenance_action(pred, anomaly, causes, sample)

    print("\nMachine", i)
    print("Prediction:", "FAILURE" if pred else "NORMAL")
    print("Risk Level:", risk)
    print("Confidence:", confidence)
    print("Anomaly:", "YES" if anomaly == -1 else "NO")
    print("Root Causes:", causes)
    print("Action:", action)

    time.sleep(1)

from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nReport:\n", classification_report(y_test, y_pred))

print("\nMissed Failures:", ((y_test == 1) & (y_pred == 0)).sum())

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.show()

import matplotlib.pyplot as plt

counts = y.value_counts()

plt.figure()
plt.bar(counts.index.astype(str), counts.values)
plt.title("Class Distribution (Machine Failure)")
plt.xlabel("Class (0 = Normal, 1 = Failure)")
plt.ylabel("Count")
plt.show()

from sklearn.metrics import precision_recall_curve

precision, recall, _ = precision_recall_curve(y_test, prob)

plt.figure()
plt.plot(recall, precision)
plt.title("Precision-Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

feature_means = np.mean(X_resampled, axis=0)

importance_scores = []

base_pred = model.predict(X_test_scaled, verbose=0).flatten()

for i in range(X_test_scaled.shape[1]):
    modified = X_test_scaled.copy()
    modified[:, i] = feature_means[i]  # use mean instead of 0

    new_pred = model.predict(modified, verbose=0).flatten()

    impact = np.mean(np.abs(base_pred - new_pred))
    importance_scores.append(impact)

plt.figure()
plt.bar(range(len(feature_names)), importance_scores)
plt.xticks(range(len(feature_names)), feature_names, rotation=90)
plt.title("Feature Importance (Model Impact)")
plt.show()

plt.figure()
plt.hist(mse, bins=50)
plt.axvline(anomaly_threshold)
plt.title("Reconstruction Error Distribution")
plt.xlabel("MSE")
plt.ylabel("Frequency")
plt.show()

final_scores = 0.7 * prob + 0.3 * np.minimum(mse / anomaly_threshold, 1)

plt.figure()
plt.hist(final_scores, bins=50)
plt.title("Final Risk Score Distribution")
plt.xlabel("Risk Score")
plt.ylabel("Frequency")
plt.show()

sample_probs = prob[:20]

plt.figure()
plt.plot(sample_probs)
plt.axhline(0.3)
plt.title("Prediction Probabilities (Sample)")
plt.xlabel("Sample Index")
plt.ylabel("Failure Probability")
plt.show()